services:

  api:
    build: .
    container_name: accento-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: accento-worker
    env_file:
      - .env
    command: celery -A app.workers.celery_worker worker --loglevel=INFO --concurrency=1 --pool=solo
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7
    container_name: accento-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: accento-mongo
    command:
      [
        "mongod",
        "--quiet",
        "--setParameter",
        "logComponentVerbosity={network: {verbosity: -1}}"
      ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: